#:schema https://mise.en.dev/schema/mise.json

[deps.opentofu]
auto = true
sources = [".terraform.lock.hcl", "main.tf"]
outputs = [".terraform/"]
run = "fnox exec -- tofu init"
dir = "./infra"

[tasks."build:router"]
description = "Build routing script."
run = "npm exec wrangler -- deploy --dry-run --outdir=${MISE_PROJECT_ROOT}/dist/router"

[tasks."build:website"]
description = "Build website."
run = "npm exec vitepress -- build ${MISE_PROJECT_ROOT}/src/website"

[tasks."dev:router"]
description = "Start development server for routing script."
run = "npm exec wrangler -- dev"

[tasks."dev:website"]
description = "Start development server for website."
run = "npm exec vitepress -- dev ${MISE_PROJECT_ROOT}/src/website"

[tasks."infra:apply"]
description = "Applies the changes required to reach the desired state of the configuration."
run = "fnox exec -- tofu -chdir=${MISE_PROJECT_ROOT}/infra apply"

[tasks."infra:format"]
description = "Formats the terraform files."
run = "fnox exec -- tofu -chdir=${MISE_PROJECT_ROOT}/infra fmt"

[tasks."infra:plan"]
description = "Generates an execution plan for infrastructure."
run = "fnox exec -- tofu -chdir=${MISE_PROJECT_ROOT}/infra plan"

[tasks."infra:validate"]
description = "Validates the terraform files."
run = "fnox exec -- tofu -chdir=${MISE_PROJECT_ROOT}/infra validate"
